### ISSUE TITLE
Do you want to cooperate around one lib?

### ISSUE THREAD

**Issue by fede4ka1245** [sbcrmweb/react-ymaps3#3]
Hey! See your work around ymap3-components lib and yandex maps. Great work!

I Invite you as a collaborator to ymap3-components. I think that working together is a better way to make a nice api for developers. So, I hope u will accept it :З

**Comment by antokhio** [comment]
Hi, yes, i'm up, just gonna be easier if you tag me directly @antokhio, still need to do more testing but busy on schedule, fill free to tag me if you need any kind of advisee or help with something.
